import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/lib/providers/ReduxProvider";
import PersistantProvider from "@/lib/providers/PersistantProvider";





export const metadata: Metadata = {
  title: "Meena",
  description: "Generated by meena",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="fr">

      <body className="flex flex-col items-center h-dvh w-full">
        <ReduxProvider>
          <PersistantProvider>
            <main className='flex flex-row w-full h-dvh'>
              {children}
            </main>
          </PersistantProvider>
        </ReduxProvider>
      </body>

    </html>
  );
}
