import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
import ReduxProvider from "@/lib/providers/ReduxProvider";
import PersistantProvider from "@/lib/providers/PersistantProvider";



export const metadata: Metadata = {
  title: "Meena",
  description: "Generated by meena",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">

      <body className="flex flex-col items-center h-dvh">
        <ReduxProvider>
          <PersistantProvider>
            {children}
            <ToastContainer position="top-center" autoClose={3000} theme="colored" />
          </PersistantProvider>
        </ReduxProvider>
      </body>

    </html>
  );
}
